### ISSUE TITLE
Auto-acquisition fails (Whisper model:medium)

### ISSUE THREAD

**Issue by kuguma** [axinc-ai/ailia-models#1068]
try:
`python .\whisper.py -m medium`

result:
```
 INFO utils.py (13) : Start!
 INFO utils.py (163) : env_id: 2
 INFO utils.py (166) : cuDNN-NVIDIA GeForce RTX 3080 (8.6, FP32)
 INFO model_utils.py (69) : Downloading onnx file... (save path: encoder_medium..optonnx)
Traceback (most recent call last):
  File "C:\axell\ailia-models\audio_processing\whisper\whisper.py", line 910, in <module>
    main()
  File "C:\axell\ailia-models\audio_processing\whisper\whisper.py", line 865, in main
    check_and_download_models(WEIGHT_ENC_PATH, MODEL_ENC_PATH, REMOTE_PATH)
  File "C:\axell\ailia-models\audio_processing\whisper\../../util\model_utils.py", line 70, in check_and_download_models
    urlretrieve(
  File "C:\axell\ailia-models\audio_processing\whisper\../../util\model_utils.py", line 38, in urlretrieve
    urllib.request.urlretrieve(
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\k\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by kyakuno** [comment]
URLが間違っていたので修正しました。

**Comment by zhangqianYY** [comment]
try:
`python whisper.py --input demo.wav --model_type medium  --dynamic_kv_cache --normal --onnx`
result:
```
 INFO arg_utils.py (13) : Start!
WARNING arg_utils.py (26) : ailia package cannot be found under `sys.path`
WARNING arg_utils.py (27) : default env_id is set to 0, you can change the id by [--env_id N]
 INFO model_utils.py (86) : ONNX file and Prototxt file are prepared!
 INFO model_utils.py (71) : Downloading onnx file... (save path: decoder_medium.onnx)
https://storage.googleapis.com/ailia-models/whisper/decoder_medium.onnx
Traceback (most recent call last):
  File "whisper.py", line 941, in <module>
    main()
  File "whisper.py", line 895, in main
    check_and_download_models(WEIGHT_DEC_PATH, MODEL_DEC_PATH, REMOTE_PATH)
  File "../../util\model_utils.py", line 75, in check_and_download_models
    progress_print,
  File "../../util\model_utils.py", line 42, in urlretrieve
    progress_print,
  File "D:\softwares\Python37\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\softwares\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\softwares\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\softwares\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\softwares\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\softwares\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\softwares\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
https://storage.googleapis.com/ailia-models/whisper/decoder_medium.onnx ,HTTP Error 404: Not Found @kyakuno
