### ISSUE TITLE
Re-export StabldDiffusion

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1187]
StableDiffusionのdiffusion_emb, mid, outを1モデルでエクスポートしたい。
外部pbでも良い。

- FP32
- FP16
の2モデルが欲しい。

**Comment by kyakuno** [comment]
解像度が256x256で出力できない（絵が壊れる）という問題も可能であれば解消したい。

**Comment by kyakuno** [comment]
autoencoderのinitializerのdimsが512になっているのが気になる。

```
  initializer {
      dims: 512
      dims: 1
      dims: 1
      data_type: 1
      name: "onnx::Add_911"
  }
  initializer {
      dims: 512
      data_type: 10
      name: "onnx::Conv_912"
  }
```

**Comment by kyakuno** [comment]
1. autoencoderの可変解像度対応（優先度高）
2. emb、mid、outの統合（優先度低）

**Comment by kyakuno** [comment]
前回のエクスポート
https://github.com/axinc-ai/ailia-models/issues/900

**Comment by kyakuno** [comment]
変換元
https://github.com/CompVis/stable-diffusion

**Comment by kyakuno** [comment]
下記のコマンドでtxt2imgが実行できる。

```
python3 scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
```

下記のエラーが発生するので、ldmフォルダをscriptsフォルダにコピーする。

```
ModuleNotFoundError: No module named 'ldm'

Copying 'ldm' folder in stable-diffusion-main to 'scripts' folder. That's how I solve this problem. It begins to run with other problems occurring.
```

https://github.com/CompVis/stable-diffusion/issues/261

**Comment by kyakuno** [comment]
```
 No such file or directory: 'models/ldm/stable-diffusion-v1/model.ckpt'
```

**Comment by kyakuno** [comment]
前回はsd-v1-4.ckptでエクスポートしている。

**Comment by kyakuno** [comment]
```
ModuleNotFoundError: No module named 'taming'
```

のエラーは-eオプションを付与してインストールが必要。

```
pip3 install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
pip3 install -e git+https://github.com/openai/CLIP.git@main#egg=clip
```

このオプションを付与するとローカルにインストールされる。

**Comment by kyakuno** [comment]
modules.pyのcudaを下記に書き換え。

```
'cuda' if torch.cuda.is_available() else 'cpu'
```

**Comment by kyakuno** [comment]
txt2img.pyに下記を追加。

```
                # Export auto encoder
                onnx_export = True
                if onnx_export:
                    model.forward = model.first_stage_model.decode
                    samples_ddim = torch.from_numpy(np.zeros((2,4,64,64), dtype=np.float32))
                    output = model.first_stage_model.decode(samples_ddim)
                    print(output.shape)
                    torch.onnx.export(
                        model, [samples_ddim], 'autoencoder2.onnx',
                        input_names=["input"],
                        output_names=["output"],
                        dynamic_axes={
                            'input': {0: 'n', 2: 'h', 3: 'w'}
                        },
                        verbose=False, opset_version=11
                    )
                    sys.exit(1)
```

**Comment by kyakuno** [comment]
再エクスポートした場合、モデルサイズが99.1MB -> 198.9MBに大きくなるが、これは元のモデルがFP16でエクスポートされているため。

**Comment by kyakuno** [comment]
再エクスポートしたONNXでも--W 256 --H 256で出力が異常になる。

**Comment by kyakuno** [comment]
エクスポート時に256x256にしてみる。

```
python3 scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms -w 256 -h 256
```

**Comment by kyakuno** [comment]
明示的に256x256にしても正常な画像が出力されないので、AutoEncoderではなく、Diffusionの方に問題があるのかも。

**Comment by kyakuno** [comment]
diffusionのエクスポート。

```
class DiffusionWrapper(pl.LightningModule):
    def __init__(self, diff_model_config, conditioning_key):
        super().__init__()
        self.diffusion_model = instantiate_from_config(diff_model_config)
        self.conditioning_key = conditioning_key
        assert self.conditioning_key in [None, 'concat', 'crossattn', 'hybrid', 'adm']

    def forward(self, x, t, c_concat: list = None, c_crossattn: list = None):
        from torch.autograd import Variable
        xx = (Variable(x.type(torch.float32)), Variable(t), Variable(cc))
        torch.onnx.export(
            self.diffusion_model, xx, 'diffusion.onnx',
            input_names=["x", "timesteps", "context"],
            output_names=["out"],
            dynamic_axes={'x': {0:'n', 2:'h',3:'w'}, 'timesteps': {0:'n'}, 'context': {0:'n', 1:'l'}},
            verbose=False, opset_version=12
        )
        import sys
        sys.exit(1)
```

**Comment by kyakuno** [comment]
256x256の場合は512x512よりも多くのステップ数を重ねないといけないだけみたい。512x512では5stepsでもそれっぽい絵が出るが、256x256だと20stepsぐらいないとまともな絵にならない。

**Comment by kyakuno** [comment]
diffusionを1モデルでエクスポートしようとすると下記のエラー。

```
Sampling:   0%|                                           | 0/2 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/txt2img.py", line 371, in <module>
    main()
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/txt2img.py", line 322, in main
    samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/plms.py", line 97, in sample
    samples, intermediates = self.plms_sampling(conditioning, size,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/plms.py", line 152, in plms_sampling
    outs = self.p_sample_plms(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/plms.py", line 218, in p_sample_plms
    e_t = get_model_output(x, t)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/plms.py", line 185, in get_model_output
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/models/diffusion/ddpm.py", line 1413, in forward
    torch.onnx.export(
  File "/usr/local/lib/python3.11/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.11/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/modules/diffusionmodules/openaimodel.py", line 732, in forward
    h = module(h, emb, context)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/modules/diffusionmodules/openaimodel.py", line 83, in forward
    x = layer(x, emb)
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/modules/diffusionmodules/openaimodel.py", line 250, in forward
    return checkpoint(
           ^^^^^^^^^^^
  File "/Users/kyakuno/Desktop/stable-diffusion/scripts/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unordered_map::at: key not found
```

**Comment by kyakuno** [comment]
下記に沿って、flags = Falseにすると問題ない。
https://github.com/axinc-ai/ailia-models/issues/900#issuecomment-1563004564

```
def checkpoint(func, inputs, params, flag):
    """
    Evaluate a function without caching intermediate activations, allowing for
    reduced memory at the expense of extra compute in the backward pass.
    :param func: the function to evaluate.
    :param inputs: the argument sequence to pass to `func`.
    :param params: a sequence of parameters `func` depends on but does not
                   explicitly take as arguments.
    :param flag: if False, disable gradient checkpointing.
    """
    flag = False
    if flag:
        args = tuple(inputs) + tuple(params)
        return CheckpointFunction.apply(func, len(inputs), *args)
    else:
        return func(*inputs)
```

**Comment by kyakuno** [comment]
分割しない場合、2GBを超えるので外部pbになる。

**Comment by kyakuno** [comment]
FP32で合計で3.64GBなので、WindowsでFP16でエクスポートすれば1つのONNXに入るかもしれない。

**Comment by kyakuno** [comment]
作業リポジトリ
https://github.com/axinc-ai/stable-diffusion

**Comment by kyakuno** [comment]
basilmixもエクスポートした。
https://storage.googleapis.com/ailia-models/stable-diffusion-txt2img/basil_mix.opt.onnx
https://storage.googleapis.com/ailia-models/stable-diffusion-txt2img/basil_mix.opt.onnx.prototxt
