### ISSUE TITLE
Makedirs error

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1221]
```
kyakuno@KazukinoMacBook-Pro detic % python3 detic.py -i tree.jpeg -e 0 -s output.jpg
 INFO arg_utils.py (13) : Start!
 INFO arg_utils.py (163) : env_id: 0
 INFO arg_utils.py (166) : CPU
 INFO model_utils.py (84) : ONNX file and Prototxt file are prepared!
WARNING detic.py (487) : This model do not work on FP16. So use CPU mode.
 INFO detic.py (381) : tree.jpeg
 INFO detic.py (388) : Start inference...
 INFO detic.py (407) : detected 1 instances
Traceback (most recent call last):
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/object_detection/detic/detic.py", line 515, in <module>
    main()
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/object_detection/detic/detic.py", line 511, in main
    recognize_from_image(net)
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/object_detection/detic/detic.py", line 413, in recognize_from_image
    savepath = get_savepath(args.savepath, image_path, ext='.png')
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/object_detection/detic/../../util/arg_utils.py", line 256, in get_savepath
    os.makedirs(dirname, exist_ok=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by kyakuno** [comment]
#1213 の不具合。
