### ISSUE TITLE
ADD Dain

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#417]
Frame interpolation

https://github.com/baowenbo/DAIN
MIT

DAIN ncnn vulkan
https://github.com/nihui/dain-ncnn-vulkan

**Comment by ooe1123** [comment]
以下のエラーのため、特定のバージョンのscipyを入れる。
pip install scipy==1.1.0
```
Traceback (most recent call last):
  File "demo_MiddleBury.py", line 13, in <module>
    from scipy.misc import imread, imsave
ImportError: cannot import name 'imread' from 'scipy.misc' (/usr/local/lib/python3.7/dist-packages/scipy/misc/__init__.py)
```

**Comment by ooe1123** [comment]
CUDAエクステンションをビルドするために、pytorch==1.4.0 以前を入れる。

**Comment by ooe1123** [comment]
試しにエクスポートを試みると以下のエラーが発生する。
```
  File "/content/DAIN/PWCNet/correlation_package_pytorch1_0/correlation.py", line 59, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
RuntimeError: Attempted to trace CorrelationFunction, but tracing of legacy functions is not supported
```

torch.autograd.Function を継承したモジュールを使っているのが原因のようだったので、
torch.autograd.Function を単純に torch.nn.Module に置き換えてみたが、以下の別のエラーが発生する。
```
  File "/content/DAIN/PWCNet/correlation_package_pytorch1_0/correlation.py", line 30, in forward
    self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)
IndexError: _Map_base::at
```
