### ISSUE TITLE
OpenCV error in hand_detection/hand_detection_pytorch.py

### ISSUE THREAD

**Issue by itsmeterada** [axinc-ai/ailia-models#592]
$ python hand_detection_pytorch.py -i CARDS_OFFICE.jpg -s out.png
 INFO utils.py (13) : Start!
 INFO utils.py (155) : env_id: 3
 INFO model_utils.py (67) : ONNX file and Prototxt file are prepared!
 INFO hand_detection_pytorch.py (54) : CARDS_OFFICE.jpg
 INFO hand_detection_pytorch.py (57) : input image shape: (720, 1280, 3)
 INFO hand_detection_pytorch.py (62) : Start inference...
Traceback (most recent call last):
  File "hand_detection_pytorch.py", line 148, in <module>
    main()
  File "hand_detection_pytorch.py", line 144, in main
    recognize_from_image()
  File "hand_detection_pytorch.py", line 77, in recognize_from_image
    cv2.rectangle(
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2

**Comment by itsmeterada** [comment]
Fixed
