### ISSUE TITLE
bert_question_answering does not work with latest transformers(package)

### ISSUE THREAD

**Issue by mmitti** [axinc-ai/ailia-models#652]
* cannot import transformers.tokenization_auto.AutoTokenizer
* squad_convert_examples_to_features raises internal error (try import AutoTokenizer with `from transformers.models.auto.tokenization_auto import AutoTokenizer`)
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\library\venv\_python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\library\venv\_python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\data\processors\squad.py", line 134, in squad_convert_example_to_features
    sub_tokens = tokenizer.tokenize(token, add_prefix_space=True)
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\tokenization_utils_fast.py", line 314, in tokenize
    return self.encode_plus(text=text, text_pair=pair, add_special_tokens=add_special_tokens, **kwargs).tokens()
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\tokenization_utils_base.py", line 2494, in encode_plus
    return self._encode_plus(
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 173, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\tokenization_utils_fast.py", line 479, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 163, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
TypeError: _batch_encode_plus() got an unexpected keyword argument 'add_prefix_space'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\bert_question_answering.py", line 312, in <module>
    main()
  File ".\bert_question_answering.py", line 207, in main
    features_list = [
  File ".\bert_question_answering.py", line 208, in <listcomp>
    squad_convert_examples_to_features(
  File "D:\library\venv\ax-ailia-models\lib\site-packages\transformers\data\processors\squad.py", line 377, in squad_convert_examples_to_features
    features = list(
  File "D:\library\venv\ax-ailia-models\lib\site-packages\tqdm\std.py", line 1168, in __iter__
    for obj in iterable:
  File "D:\library\venv\_python38\lib\multiprocessing\pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "D:\library\venv\_python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
TypeError: _batch_encode_plus() got an unexpected keyword argument 'add_prefix_space'
```

**Comment by mmitti** [comment]
transformers==3.4.0 will work, but transformers==4.12.4 got above error.

**Comment by kyakuno** [comment]
`import transformers.tokenization_auto.AutoTokenizer`
を
`import transformers.AutoTokenizer`
に変更する必要がある。

また、M1 Macだと
`from transformers.data import SquadExample, squad_convert_examples_to_features`
でillegal instructionが出る。

`zsh: illegal hardware instruction`

**Comment by kyakuno** [comment]
squad_convert_examples_to_featuresからRobertaTokenizer判定でadd_prefix_space=Trueが付与される。
https://github.com/huggingface/transformers/blob/master/src/transformers/data/processors/squad.py

**Comment by kyakuno** [comment]
tokenizer.__class__.__name__をprintするとRobertaTokenizerFastとなる。

**Comment by kyakuno** [comment]
下記ではtransformers==3.5.1に戻すようにとのこと。
https://itch.io/t/1100931/error-in-ai-console-add-prefix-space

**Comment by kyakuno** [comment]
このコミットからRobertaTokenizerにadd_prefix_space=Trueが付与されている。
https://github.com/huggingface/transformers/commit/ba5ea66e301bd78de15cc00a3a4c7ed13b992900
その後、RobertaTokenizerFastにも付与されるようになった。
https://github.com/huggingface/transformers/commit/3a40cdf58d8b7233e561d1bf9e76f2ed02d9c4b7#diff-79cf62e2b3263b49a09f39f5ead84886071fd8b170686dd7d2be24e6bcfc1344

**Comment by kyakuno** [comment]
これを見ると、tokenizerのインスタンス時にadd_prefix_spaceを渡すべきで、tokenizeにはadd_prefix_spaceを与えられないと書かれている。
https://github.com/huggingface/transformers/issues/13868

`No, the latter is not possible. I see what you were saying at first, the doc should indeed be adapted to remove the part "when you call it"`

**Comment by kyakuno** [comment]
大元のonnx_transformersもtransformer4に対応していない。
https://github.com/patil-suraj/onnx_transformers/issues/9

**Comment by kyakuno** [comment]
deepset/roberta-base-squad2そのものはpipeline経由では動いた。

```
    from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline

    model_name = "deepset/roberta-base-squad2"

    # a) Get predictions
    nlp = pipeline('question-answering', model=model_name, tokenizer=model_name)
    QA_input = {
        'question': 'Why is model conversion important?',
        'context': 'The option to convert models between FARM and transformers gives freedom to the user and let people easily switch between frameworks.'
    }
    res = nlp(QA_input)
    print(res)

    # b) Load model & tokenizer
    model = AutoModelForQuestionAnswering.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
```

下記のコードを見ると、tokenizerがis_fastの場合はsquad_convert_examples_to_featuresを呼ばないコードになっている。
https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/question_answering.py

**Comment by kyakuno** [comment]
Transformer4のpipelineの前処理と後処理を適用することで適切に推論できることを確認。

**Comment by kyakuno** [comment]
1. 公式のtransformersにおいて、従来のSquadのサンプルでは、tokenizerがis_fast属性を持っていてもsquad_convert_examples_to_featuresを読べていたが、最新版のpipelineでは自前で前処理をする形になっている
2. 今回使用しているdeepset/roberta-base-squad2はis_fast属性を持っているため、自前の前処理を実装する必要がある
