### ISSUE TITLE
dsfd not worked on Video Mode

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#783]
```
/usr/local/opt/python@3.9/bin/python3.9 dsfd.py --video 0 --env_id 2 --benchmark_count 5
 INFO utils.py (13) : Start!
 INFO utils.py (163) : env_id: 2
 INFO utils.py (166) : MPSDNN-Apple M1 Max
 INFO model_utils.py (84) : ONNX file and Prototxt file are prepared!
Traceback (most recent call last):
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/face_detection/dsfd/dsfd.py", line 148, in <module>
    main()
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/face_detection/dsfd/dsfd.py", line 144, in main
    recognize_from_image(net)
  File "/Users/kyakuno/Desktop/repos/ailia-models-ax/face_detection/dsfd/dsfd.py", line 95, in recognize_from_image
    for image_path in args.input:
TypeError: 'NoneType' object is not iterable
```

**Comment by kyakuno** [comment]
DSFDはまで未マージだった。
