### ISSUE TITLE
apply optimizer to mask_rcnn model

### ISSUE THREAD

**Issue by kzmogi** [axinc-ai/ailia-models#786]
https://github.com/axinc-ai/ailia-models/tree/master/object_detection/maskrcnn
https://github.com/axinc-ai/ailia-models/tree/master/pose_estimation_3d/3dmppe_posenet

Above models are using `mask_rcnn_R_50_FPN_1x.onnx`.

This model uses eltwise mul+add instead of batchnorm to achieve the same result.

![image](https://user-images.githubusercontent.com/43570021/162129003-51d2e0a9-2449-402a-ba82-84b27312fab2.png)

By applying the optimizer, conv+mul+add can be converted to conv ( with adjusting convolution weights and bias ).

![image](https://user-images.githubusercontent.com/43570021/162129019-64e7cbdc-ec4d-42b0-8a46-e7353fe63ce9.png)

After optimization, memory consumption is reduced to 1/4, and even a 4GB VRAM GPU can infer with vulkan without error.

**Comment by kzmogi** [comment]
The original model has an no-enough-memory error with GTX1650.

```
% python maskrcnn.py -e 7
 INFO utils.py (13) : Start!
 INFO utils.py (163) : env_id: 7
 INFO utils.py (166) : VulkanDNN-NVIDIA GeForce GTX 1650
 INFO model_utils.py (84) : ONNX file and Prototxt file are prepared!
 INFO maskrcnn.py (178) : demo.jpg
 INFO maskrcnn.py (184) : Start inference...
Traceback (most recent call last):
  File "maskrcnn.py", line 269, in <module>
    main()
  File "maskrcnn.py", line 265, in main
    recognize_from_image()
  File "maskrcnn.py", line 193, in recognize_from_image
    boxes, labels, scores, masks = net.predict([input_data])
  File "C:\opt\Python36\lib\site-packages\ailia\wrapper.py", line 363, in predict
    self.update()
  File "C:\opt\Python36\lib\site-packages\ailia\wrapper.py", line 679, in update
    core.check_error(code, self.__net)
  File "C:\opt\Python36\lib\site-packages\ailia\core.py", line 697, in check_error
    raise e(detail)
ailia.core.AiliaResourceInsufficientException: code: -5 (There is no enough memory space.)
+ error detail : Layer:2796(Reshape_DNN) Error:Vulkan Error (C:\src\ailia\library\dnn\vulkan\vulkan_common.h:929): -2
```

**Comment by kzmogi** [comment]
The optimized model has no error with GTX1650.

```
% python maskrcnn.py -e 7
 INFO utils.py (13) : Start!
 INFO utils.py (163) : env_id: 7
 INFO utils.py (166) : VulkanDNN-NVIDIA GeForce GTX 1650
 INFO model_utils.py (84) : ONNX file and Prototxt file are prepared!
 INFO maskrcnn.py (178) : demo.jpg
 INFO maskrcnn.py (184) : Start inference...
 INFO maskrcnn.py (198) : saved at : output.png
 INFO maskrcnn.py (206) : Script finished successfully.
```
