### ISSUE TITLE
module 'ailia' has no attribute 'DETECTOR_ALGORITHM_SSD'

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#85]
- requirements.txtのために`mobilenet_ssd`を実行している際に発覚したエラー
- ailia version 1.2.2

```bash
ONNX file and Prototxt file are prepared!
env_id: 1
Traceback (most recent call last):
  File "mobilenet_ssd.py", line 189, in <module>
    main()
  File "mobilenet_ssd.py", line 185, in main
    recognize_from_image()
  File "mobilenet_ssd.py", line 115, in recognize_from_image
    algorithm=ailia.DETECTOR_ALGORITHM_SSD, env_id=env_id
AttributeError: module 'ailia' has no attribute 'DETECTOR_ALGORITHM_SSD'
```

**Comment by kyakuno** [comment]
1.2.2のailiaの__init__.pyとcore.pyでsite_pacakageのものを上書きすると通ると思います。

**Comment by sngyo** [comment]
両方バージョンを合わせないといけないのを見落としていました．動作確認できたので閉めます．ありがとうございました．
