### ISSUE TITLE
lightweight-human-pose-estimation: ailia.core.AiliaFileIoException: code: -2 (Failed to access the file.)

### ISSUE THREAD

**Issue by neebdev** [axinc-ai/ailia-models#925]
Lightweight human pose estimation is not working with video file or webcam.

INFO utils.py (13) : Start!
 INFO utils.py (163) : env_id: 4
 INFO utils.py (166) : cuDNN-NVIDIA GeForce GTX 1660 Ti with Max-Q Design (7.5, FP32)
 INFO model_utils.py (84) : ONNX file and Prototxt file are prepared!
Traceback (most recent call last):
  File "D:\AI\ailia-models\pose_estimation\lightweight-human-pose-estimation\lightweight-human-pose-estimation.py", line 250, in <module>
    main()
  File "D:\AI\ailia-models\pose_estimation\lightweight-human-pose-estimation\lightweight-human-pose-estimation.py", line 243, in main
    recognize_from_video()
  File "D:\AI\ailia-models\pose_estimation\lightweight-human-pose-estimation\lightweight-human-pose-estimation.py", line 191, in recognize_from_video
    pose = ailia.PoseEstimator(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\ailia\wrapper.py", line 1186, in __init__
    super().__init__(stream_path, weight_path, env_id, num_thread, memory_mode=memory_mode, debug_log=debug_log, enable_layer_fusion=enable_layer_fusion)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\ailia\wrapper.py", line 239, in __init__
    self._open_weight(weight)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\ailia\wrapper.py", line 270, in _open_weight
    core.check_error(code, self.__net)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\ailia\core.py", line 769, in check_error
    raise e(detail)
ailia.core.AiliaFileIoException: code: -2 (Failed to access the file.)
+ error detail : File read failed.

**Comment by itsmeterada** [comment]
It's working fine on my Windows 10 / RTX3090 / cuDNN-NVIDIA environment with ailia 1.2.12.

Did you put the license file sent to your email to the right place ?
(C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\ailia\)

**Comment by neebdev** [comment]
I solved the problem. I deleted the onnx and prototxt files and it worked fine after redownloading them. The license file was in the right place. All other models were working fine except this.
